name: Build and Upload Debian Package

on:
  push:
    branches:
      - Master
  pull_request:
    branches:
      - Master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Debian package
        run: |
          chmod +x build_deb.sh
          ./build_deb.sh

      - name: Upload Debian Package Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flipclock-screensaver-packages
          path: releases/*.deb
          if-no-files-found: error
